# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0009_auto_20160427_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='current_command',
        ),
        migrations.RemoveField(
            model_name='job',
            name='error',
        ),
        migrations.RemoveField(
            model_name='job',
            name='exit_code',
        ),
        migrations.RemoveField(
            model_name='job',
            name='output',
        ),
        migrations.AddField(
            model_name='job',
            name='log',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
