# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0011_auto_20160505_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='running',
            field=models.BooleanField(default=False),
        ),
    ]
