# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 10:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0012_job_running'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='running',
        ),
    ]
