# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0013_remove_job_running'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputkey',
            name='include_val_in_job_title',
            field=models.BooleanField(default=False),
        ),
    ]
